const { network } = window.webapis;

export const {
    getVersion,
    isConnectedToGateway,
    getIpMode,
    getSubnetMask,
    getGateway,
    getMac,
    getDns,
    getIp,
    getTVName,
    getActiveConnectionType,
    addNetworkStateChangeListener,
    removeNetworkStateChangeListener,
    getWiFiSsid,
    getWiFiSignalStrengthLevel,
    getWiFiSecurityMode,
    getWiFiEncryptionType,
    getSecondaryDns,
    setDhcpOption60Field,
    removeDhcpOption60Field,
    getCurrentDhcpOption60Field,
    checkCurrentIpWith60Field,
    NetworkIpMode,
    NetworkActiveConnectionType,
    NetworkState,
    NetworkWiFiSecurityMode,
    NetworkWiFiEncryptionType
} = network;
